'use strict'

Feature('Defendants Enter details of claim')

Scenario('I can fill in Claimant organization, more Defendant details and update their details', (I, userSteps, defendantSteps) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  userSteps.enterYourOrganisationNamePage()
  userSteps.enterYourOrganisationAddress()
  userSteps.enterYourOrganisationContactDetails()
  userSteps.enterYourReferenceNumber()
  userSteps.enterYourPreferredCountyCourt()
  userSteps.enterClaimantTypeOrganisation()
  I.see('Claimant: Abc corporation')
  userSteps.enterClaimantAddress()
  userSteps.noAdditionalClaimant()
  defendantSteps.enterDefendantTypeOrganisation()
  I.see('Defendant: Def corporation')
  defendantSteps.enterDefendantAddress()
  defendantSteps.enterDefendantRepsCompanyName()
  I.see("Defendant's legal representative: Defendant Rep Ltd")
  defendantSteps.enterDefendantRepsAddress()
  defendantSteps.enterAnotherDefendant()
  defendantSteps.enterAnotherDefendantTypeIndividual()
  I.see('Defendant 2: Mrs Orange')
  defendantSteps.enterDefendantAddress()
  defendantSteps.noDefendantCompanyName()
  defendantSteps.enterServiceAddress()
  defendantSteps.enterAnotherDefendant()
  defendantSteps.enterAnotherDefendantTypeOrganisation()
  I.see('Defendant 3: Ghi corporation')
  defendantSteps.enterDefendantAddress()
  defendantSteps.enterDefendantRepsCompanyName()
  I.see("Defendant 3's legal representative: Defendant Rep Ltd")
  defendantSteps.enterDefendantRepsAddress()
  defendantSteps.verifyAndChangeDefendantDetails()
})

Scenario('I can fill in Claimant individual and Defendant individual details', (I, userSteps, defendantSteps) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  userSteps.enterYourOrganisationNamePage()
  userSteps.enterYourOrganisationAddress()
  userSteps.enterYourOrganisationContactDetails()
  userSteps.enterYourReferenceNumber()
  userSteps.enterYourPreferredCountyCourt()
  userSteps.enterClaimantTypeIndividual()
  I.see('Claimant: Mr Benugo')
  userSteps.enterClaimantAddress()
  userSteps.noAdditionalClaimant()
  defendantSteps.enterDefendantTypeIndividual()
  I.see('Defendant: Mr Pret')
  defendantSteps.enterDefendantAddress()
  defendantSteps.noDefendantCompanyName()
  defendantSteps.defendantAddressAsServiceAddress()
  defendantSteps.noAnotherDefendant()
})

Scenario('Check Error Messages in Enter your defendant type Page', (I, userSteps, defendantType) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  defendantType.open()
  defendantType.checkMandatoryErrorMessageForChooseDefendant()
  defendantType.checkMandatoryErrorMessageForOrganisationName()
  defendantType.checkForBlankErrorMessageForOrganisationName()
  defendantType.checkMandatoryErrorMessageForIndividualName()
  defendantType.checkForBlankErrorMessageForIndividualName()
})

Scenario('Check Error Messages in Enter your defendant address Page', (I, userSteps, defendantType, defendantSteps, defendantAddress) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  defendantType.open()
  defendantSteps.enterDefendantTypeOrganisation()
  I.see('Defendant: Def corporation')
  defendantAddress.checkMandatoryErrorMessage()
  defendantAddress.checkForBlankErrorMessage()
  defendantAddress.checkForIndividualMessage()
  defendantAddress.checkForAddressLineLength()
  defendantAddress.checkForPostCodeLengthMessage()
})

Scenario('Check Error Messages in Enter your defendant representative Page', (I, userSteps, defendantType, defendantSteps, defendantRepresentative) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  defendantType.open()
  defendantSteps.enterDefendantTypeOrganisation()
  I.see('Defendant: Def corporation')
  defendantSteps.enterDefendantAddress()
  defendantRepresentative.checkMandatoryErrorMessage()
  defendantRepresentative.checkMandatoryErrorMessageForDefendantCompanyName()
  defendantRepresentative.checkForBlankErrorMessageForDefendantCompanyName()
})

Scenario('Check Error Messages in Enter your defendant representative address Page', (I, userSteps, defendantType, defendantSteps, defendantRepresentativeAddress) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  defendantType.open()
  defendantSteps.enterDefendantTypeOrganisation()
  I.see('Defendant: Def corporation')
  defendantSteps.enterDefendantAddress()
  defendantSteps.enterDefendantRepsCompanyName()
  defendantRepresentativeAddress.checkMandatoryErrorMessage()
  defendantRepresentativeAddress.checkForBlankErrorMessage()
  defendantRepresentativeAddress.checkForIndividualMessage()
  defendantRepresentativeAddress.checkForAddressLineLength()
  defendantRepresentativeAddress.checkForPostCodeLengthMessage()
})

Scenario('Check Error Messages in Enter another defendant add Page', (I, userSteps, defendantType, defendantSteps, defendantAddAnotherDefendant) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  defendantType.open()
  defendantSteps.enterDefendantTypeOrganisation()
  I.see('Defendant: Def corporation')
  defendantSteps.enterDefendantAddress()
  defendantSteps.enterDefendantRepsCompanyName()
  I.see("Defendant's legal representative: Defendant Rep Ltd")
  defendantSteps.enterDefendantRepsAddress()
  defendantAddAnotherDefendant.checkMandatoryErrorMessage()
})

Scenario('Check Error Messages on defendant service address Page', (I, userSteps, defendantType, defendantSteps, defendantAddServiceAddress) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  defendantType.open()
  defendantSteps.enterDefendantTypeOrganisation()
  I.see('Defendant: Def corporation')
  defendantSteps.enterDefendantAddress()
  defendantSteps.noDefendantCompanyName()
  I.see('Address for service')
  defendantAddServiceAddress.checkMandatoryErrorMessageForAddressForService()
  defendantAddServiceAddress.checkForBlankErrorMessage()
  defendantAddServiceAddress.checkForIndividualMessage()
  defendantAddServiceAddress.checkForPostCodeLengthMessage()
  defendantAddServiceAddress.checkForAddressLineLength()
})
