'use strict'

Feature('Defendants Enter details of claim')

Scenario('I can fill in Claimant organization and Defendant organization details', (I, userSteps, defendantSteps) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  userSteps.enterYourDetails()
  userSteps.enterYourCompanyAddress()
  userSteps.enterYourCompanyContactDetails()
  userSteps.enterYourReferenceNumber()
  userSteps.enterYourPreferredCountyCourt()
  userSteps.enterClaimantTypeOrganisation()
  I.see('Claimant: Abc corporation')
  userSteps.enterClaimantAddress()
  defendantSteps.enterDefendantTypeOrganisation()
  I.see('Defendant: Def corporation')
})

Scenario('I can fill in Claimant individual and Defendant individual details', (I, userSteps, defendantSteps) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  userSteps.enterYourDetails()
  userSteps.enterYourCompanyAddress()
  userSteps.enterYourCompanyContactDetails()
  userSteps.enterYourReferenceNumber()
  userSteps.enterYourPreferredCountyCourt()
  userSteps.enterClaimantTypeIndividual()
  I.see('Claimant: Mr Benugo')
  userSteps.enterClaimantAddress()
  defendantSteps.enterDefendantTypeIndividual()
  I.see('Defendant: Mr Pret')
})

Scenario('Check Error Messages in Enter your defendant type Page', (I, userSteps, defendantType) => {
  userSteps.loginDefaultUser()
  userSteps.startClaim()
  userSteps.enterYourDetails()
  userSteps.enterYourCompanyAddress()
  userSteps.enterYourCompanyContactDetails()
  userSteps.enterYourReferenceNumber()
  userSteps.enterYourPreferredCountyCourt()
  userSteps.enterClaimantTypeOrganisation()
  userSteps.enterClaimantAddress()
  defendantType.checkMandatoryErrorMessageForChooseDefendant()
  defendantType.checkMandatoryErrorMessageForOrganisationName()
  defendantType.checkForBlankErrorMessageForOrganisationName()
  defendantType.checkMandatoryErrorMessageForIndividualName()
  defendantType.checkForBlankErrorMessageForIndividualName()
})
